<table class="table table-striped table-bordered table-condensed">
    <thead>
        <th><center>ФИО</center></th>
        <th><center>Адрес</center></th>
        <th><center>Телефон</center></th>
        <th><center>Предприятие</center></th>
        <th><center>Создан</center></th>
        <th></th>
    </thead>
    <tbody>
<?php
    $client = $this->clients;
    $count = count($client)-1;
    for ($i = 0; $i <= $count; $i++) {
?>
    <tr>
        <td><a href="/admin/meet?client_id=<?php echo $client[$i]["client_id"]; ?>" title="Посмотреть встречи"><?php echo $client[$i]["last_name"]." "; echo $client[$i]["first_name"]." "; echo $client[$i]["middle_name"]; ?></a></td>
        <td><?php echo $client[$i]["address"]; ?></td>
        <td><?php echo $client[$i]["phone"]; ?></td>
        <td><?php echo $client[$i]["facility"]; ?></td>
        <td><?php echo $client[$i]["created"]; ?></td>
         <td style="width: 60px;"><center>
            <a class="edit-icon" href="/admin/client/edit?client_id=<?php echo $client[$i]["client_id"]; ?>" title="редактировать"></a>
            <a class="delete-icon user-delete-confirm" href="?delete=<?php echo $client[$i]["client_id"]; ?>" title="удалить"></a>
        </center></td>
    </tr>
<?php } ?>
    </tbody>
</table>